<?php

/**
 * @file
 * Contains obfuscate.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function obfuscate_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the obfuscate module.
    case 'help.page.obfuscate':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Obfuscates email addresses with a Field Formatter of Email field, a text Filter and a Twig extension.') . '</p>';
      return $output;

    default:
  }
}
