obfuscate.settings.obfuscate_field_formatter:
  type: config_object
  label: 'Obfuscate Field Formatter settings'
  mapping:
    obfuscate_method:
      type: string
      label: 'Obfuscation method'
